USE [master]
GO

/****** Object:  Database [WaterCounter]    Script Date: 10.09.2021 0:22:28 ******/
CREATE DATABASE [WaterCounter]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WaterCounter', FILENAME = N'C:\SQL\Data\WaterCounter.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WaterCounter_log', FILENAME = N'C:\SQL\Logs\WaterCounter_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [WaterCounter] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WaterCounter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WaterCounter] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WaterCounter] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WaterCounter] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WaterCounter] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WaterCounter] SET ARITHABORT OFF 
GO

ALTER DATABASE [WaterCounter] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WaterCounter] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WaterCounter] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WaterCounter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WaterCounter] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WaterCounter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WaterCounter] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WaterCounter] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WaterCounter] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WaterCounter] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WaterCounter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WaterCounter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WaterCounter] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WaterCounter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WaterCounter] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WaterCounter] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WaterCounter] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WaterCounter] SET RECOVERY FULL 
GO

ALTER DATABASE [WaterCounter] SET  MULTI_USER 
GO

ALTER DATABASE [WaterCounter] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WaterCounter] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WaterCounter] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WaterCounter] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WaterCounter] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WaterCounter] SET QUERY_STORE = OFF
GO

USE [WaterCounter]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [WaterCounter] SET  READ_WRITE 
GO


USE [WaterCounter]
GO

/****** Object:  Table [dbo].[RawData]    Script Date: 10.09.2021 0:23:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RawData](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Time] [datetime] NOT NULL,
	[WaterCounterNumber] [tinyint] NOT NULL,
	[Processed] [bit] NOT NULL,
 CONSTRAINT [PK_RawData] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RawData] ADD  CONSTRAINT [DF_RawData_Processed]  DEFAULT ((0)) FOR [Processed]
GO


/****** Object:  Index [IX_RawData_Processed]    Script Date: 10.09.2021 0:25:12 ******/
CREATE NONCLUSTERED INDEX [IX_RawData_Processed] ON [dbo].[RawData]
(
	[Processed] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


